# Numerical Computating with Numpy

Source Video, Enthought SciPy 2019
https://www.youtube.com/watch?v=ZB7BZMhfPgk&list=PLYx7XA2nY5GcDQblpQ_M1V3PQPoLWiDAC&index=2&t=0s

In [1]:
a = [1,2,3,4,5]

In [2]:
b = [14,15,16,17,18]

In [3]:
a+b

[1, 2, 3, 4, 5, 14, 15, 16, 17, 18]

# Import Numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])

In [8]:
# N dimensional
type(a)

numpy.ndarray

In [9]:
# Data Type
a.dtype

dtype('int64')

In [27]:
f = np.array([1.2, 2.3, 3.4, 4.5, 5.6])
print(type(f))
print(f.dtype)

<class 'numpy.ndarray'>
float64


### All the data has to be of the same type

In [28]:
# Strong renforcement of the data types
print(a)
a[0] = 10
print(a)
a[0] = 11.6
print(a)

[11  2  3  4  5]
[10  2  3  4  5]
[11  2  3  4  5]


### ndim, shape, size

In [29]:
# Dimensions of the Array
a.ndim

1

In [30]:
#Tuple representing the shape of the array
a.shape

(5,)

In [31]:
# number of elements in the array
a.size

5

### Basic computation of arrays (This is what we want !!!)

In [32]:
a + f

array([12.2,  4.3,  6.4,  8.5, 10.6])

In [33]:
a * f

array([13.2,  4.6, 10.2, 18. , 28. ])

In [34]:
a / f

array([9.16666667, 0.86956522, 0.88235294, 0.88888889, 0.89285714])

In [35]:
f ** a

array([7.43008371e+00, 5.29000000e+00, 3.93040000e+01, 4.10062500e+02,
       5.50731776e+03])

In [36]:
a * 10

array([110,  20,  30,  40,  50])

### Universal Functions (ufuncs)

In [38]:
np.sin(a)

array([-0.99999021,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### 2 Dimensional Arrays

In [40]:
a = np.array([[0,1,2,3], [10,11,12,13]])

In [42]:
print(type(a))
print(a.shape)
print(a.size)
print(a.ndim)

<class 'numpy.ndarray'>
(2, 4)
8
2


Accesing elements

In [45]:
# Row, Column
print(a[1,3])
print(a)

13
[[ 0  1  2  3]
 [10 11 12 13]]


In [46]:
# Single index, addresses Rows
a[1]

array([10, 11, 12, 13])

#### Indexing and Slicing <br/>
var[lower:upper:step] <br/>

In [58]:
#indices
# Negetive ...-5 -4 -3 -2 -1
# Positive ... 0  1  2  3  4
b = np.array([10,11,12,13,14])
print(b)

[10 11 12 13 14]


In [51]:
b[1:3]

array([11, 12])

In [52]:
b[1:-2]

array([11, 12])

In [54]:
b[-4:3]

array([11, 12])

In [55]:
# grab first 3 elements
b[:3]

array([10, 11, 12])

In [56]:
# grab the last 2 elements
b[-2:]

array([13, 14])

In [57]:
# every other element
b[::2]

array([10, 12, 14])